name: Frontend CI/CD

on:
  push:
    paths:
      - "frontend/**"

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - name: SET UP NODEJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependecies
        run: |
          cd frontend
          npm install
      - name: Build
        run: npm run build
